zephyr_job:
    resource: "@ZephyrJobBundle/Resources/config/routing.yml"
    prefix:   /

zephyr_user:
    resource: "@ZephyrUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"