zephyr_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: ZephyrUserBundle:Default:index }

zephyr_admin:
    path:     /admin/
    defaults: { _controller: ZephyrUserBundle:Default:admin }

zephyr_admin_edit:
    path:     /admin/edit/{id}
    defaults: { _controller: ZephyrUserBundle:Default:edit }